### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.cross_decomposition'

### ISSUE THREAD

**Issue by 10315619** [simaki/adaptive-elastic-net#28]
hi, been wanting to use adaptive elastic net, just pip installed and imported to my python script, but there seems to be an issue.
ModuleNotFoundError: No module named 'sklearn.cross_decomposition'
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18780/1107137604.py in <module>
      4 from sklearn.linear_model import LinearRegression, LassoCV, RidgeCV, Lasso, Ridge, ElasticNetCV, ElasticNet
      5 from yellowbrick.regressor import AlphaSelection
----> 6 from aenet import AdaptiveElasticNet
      7 from aenet import AdaptiveElasticNetCV

C:\python\lib\site-packages\aenet\__init__.py in <module>
      1 # flake8: noqa
      2 
----> 3 from .aen import AdaptiveElasticNet
      4 from .aencv import AdaptiveElasticNetCV

C:\python\lib\site-packages\aenet\aen.py in <module>
      4 import cvxpy
      5 import numpy as np
----> 6 from asgl import ASGL
      7 from sklearn.base import MultiOutputMixin
      8 from sklearn.base import RegressorMixin

C:\python\lib\site-packages\asgl\__init__.py in <module>
      1 from .asgl import *
----> 2 from .weights import *
      3 from .cv import CV, TVT, train_test_split

C:\python\lib\site-packages\asgl\weights.py in <module>
      3 
      4 import numpy as np
----> 5 from sklearn.cross_decomposition import PLSRegression
      6 from sklearn.decomposition import PCA
      7 from sklearn.decomposition import SparsePCA

**Comment by simaki** [comment]
Thanks for using this. Possibly the problem of sklearn. could you run `pip install -U sklearn`?
If the problem pops up even after this please provide minimal reproducible code and log.
Formatted code and log (https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) help us quickly spot the issue. Thank you

**Comment by 10315619** [comment]
sorry, my bad, after update the issue is solved

**Comment by simaki** [comment]
Glad it worked out!
